server:
  address: "corecast.bitquery.io"
  authorization: "ory_at_"
  insecure: false

stream:
  type: "dex_trades"

# dextrades sample filter
filters:
  tokens:
    - "412zDygnwP9DzitnQVgRKUFFTDmrYScFch6P2k39pump"
  # programs:
  #     - "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
  #     - "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
  #     - "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
